# -*- coding: utf-8 -*-
"""Tweepy Api: IndvsAus tweets extraction

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/112EyuQ1cehzRNJJqtiXAH9o6tK52j8ku
"""



from google.colab import drive
drive.mount('/content/drive')

!pip install tweepy
import os
import tweepy as tw

apikey = 's38c8h8E25gSVU1WW28wi7fS7'
apisecretkey = 'jLG9s4rt4QwLo6PFyMSpLVRT1IoQ3f1EwrrgzTg6GdJLUTeI5e'
accesstoken = '1347844103627698178-3HuOoCCFuMWHwLTmhswKUtJSvGUPet'
accesstokensecret = 'TH8tAcatrjTHgh81Oo7dw6rvWGGRFZoSrPDa5eInYcQ3c'

auth = tw.OAuthHandler(apikey,apisecretkey) #calling OAuthHandler required for authantication with Twitter
auth.set_access_token(accesstoken,accesstokensecret)

api = tw.API(auth,wait_on_rate_limit=True,wait_on_rate_limit_notify=True)

search_word = '#IndvsAus' or '#AusvsInd'
date_since = '2021-01-20'
date_until = '2021-01-21'

tweets = tw.Cursor(api.search,q = search_word+' -filter:retweets', lang ='en',tweet_mode='extended',since = date_since,until= date_until).items(1000)

tweet_details = [[tweet.id_str,tweet.full_text,tweet.created_at,tweet.user.location]for tweet in tweets]
tweet_details

import pandas as pd
tweet900_df = pd.DataFrame(data=tweet_details,columns=['tweet_id','Full_text','tweet_timestamp','user_location'])
pd.set_option('max_colwidth',800)
tweet900_df.head(10)

tweet900_df.to_csv(r'C:\Users\91987\Desktop\Twitter Sentiment Analysis\File Name.csv', index = False)

